# Cloudflare Pages configuration
name = "routinez"
compatibility_date = "2023-12-01"

# Pages configuration
[build]
command = "npm run build"
# Next.js export outputs to 'out' directory when using output: 'export'
output_directory = "out"

# For Cloudflare Pages, we don't need the site bucket or upload format
# Remove the conflicting [site] and [build.upload] sections