# Cloudflare Pages configuration
name = "routinez"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
# Next.js static export outputs to 'out' directory
output_dir = "out"

# Specify the build output directory for Pages
[build.output]
include = ["out/**/*"]
pages_build_output_dir = "out"